### ISSUE TITLE
もっと褒めてほしいです

### ISSUE THREAD

**Issue by RKyo65535** [ygkn/completely-understand#1]
**Is your feature request related to a problem? Please describe.**
楽しいアプリなので何度も完全に理解しているのですが、プログラムは🎉おめでとう！🎉としか言ってくれません。これは完全に理解した人に対する冒涜ではないでしょうか。

**Describe the solution you'd like**
完全に理解するたび、
🎉さすが！🎉
🎉やったね！🎉
🎉おめでとう！🎉
🎉Congratulations!!🎉
などといった違う誉め言葉を表示していただきたいです。

**Comment by ygkn** [comment]
たし :crab:

**Comment by ygkn** [comment]
できた。
thx for your contribution!
